-- Insert plan information into PlanInfo table
INSERT INTO PlanInfo
VALUES 
('UHC Bronze-X Value Plan - HMO', '376.65', '9450', '9450', '35', '35', 'No Charge', 'No Charge', '90', '90', '150', '150', 'Full Price', 'No Charge', '80', '80', '25', '25', 'Full Price', 'No Charge', 'Full Price', 'No Charge', 'Full Price', 'No Charge', 'Full Price', 'No Charge', 'Full Price', 'No Charge', '4,810', 'Additional Plan Benefits and Features - Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card: Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, Virtual Urgent Care: Get the care you need with a virtual visit, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Primary Care: Low-cost virtual primary visits are available')
('UHC Bronze-X Virtual Access (Unlimited $0 Virtual) - HMO', '378.45', '7250', '9450', 'No Charge', 'No Charge', 'No Charge', 'No Charge', 'Full Price', '30%', 'Full Price', '30%', 'Full Price', '30%', '20', '20', '3', '3', 'Full Price', '30%', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '30%', 'Full Price', '50%', '4613', 'Additional Plan Benefits and Features -  Virtual Plan with Galileo : Get unlimited $0 virtual care through the Galileo app with a UnitedHealthcare Virtual plan, Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states')
('UHC Bronze-X ($0 PCP, $5 Tier 2 Rx, No Referrals) - HMO', '379.54', '8250 ', '9450', 'No Charge', 'No Charge', 'No Charge', 'No Charge', '140', '140', 'Full Price', '40%', 'Full Price', '40%', 'Full Price', '20', '5', '5', 'Full Price', '40%', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '40%', 'Full Price', '50%', '5734', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™, you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Bronze-X Copay Focus $0 Med Ded - HMO', '386.41', '5000', '9450 ', '50', '50', 'No Charge', 'No Charge', '150', '150', '100', '100', '200', '200', '20', '20', '25', '25', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '50%', '$3000 per day', '$3000 per day', '2000', '2000', '4897', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Gold-X Copay Focus $0 Med Ded ($0 PCP) - HMO', '494.88', '500', '7000 ', 'No Charge', 'No Charge', 'No Charge', 'No Charge', '50', '50', '65', '65', '300', '300', '10', '10', '3', '3', '50', '50', 'Full Price', '45%', 'Full Price', '50%', '$1000 per day', '$1000 per day', '1000', '1000', '6011', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Gold-X Virtual Access (Unlimited $0 Virtual) - HMO', '497.65', '1100', '8400', 'No Charge', 'No Charge', 'No Charge', 'No Charge', '100', '100', 'Full Price', '25%', 'Full Price', '25%', '8', '8','3', '3', 'Full Price', '60', 'Full Price', '40%', 'Full Price', '50%', 'Full Price', '25%', 'Full Price', '25%', '6032', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Plan with Galileo: Get unlimited $0 virtual care through the Galileo app with a UnitedHealthcare Virtual plan')
-- ('UHC Silver-X Copay Focus $0 Med Ded ($0 PCP) - HMO', '503.71', '2500', '9450', 'No Charge', 'No Charge', 'No Charge', 'No Charge', '100', '100', '65', '65', '300', '300', '20', '20', '10', '10', 'Full Price', '85', 'Full Price', '40%', 'Full Price', '50%', '$2500 per stay', '$2500 per stay', '1500', '1500', '6144', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Silver-X Value Plan - HMO', '509.67', '5250', '7600', '35', '35', 'No Charge', 'No Charge', '90', '90', '150', '150', 'Full Price', '600', '80', '80', '25', '25', 'Full Price', '75', 'Full Price', '80', 'Full Price', '100', 'Full Price', '$550 per stay', 'Full Price', '500', '6406', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Silver-X ($0 PCP, $3 Tier 2 Rx, No Referrals) - HMO', '512.17', '3250', '9450', 'No Charge', 'No Charge', 'No Charge', 'No Charge', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '50%', '20', '20','3', '3', 'Full Price', '100', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '50%', 'Full Price', '50%', '6218', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Gold-X Value Plan - HMO', '512.98', '1150', '6750', '10', '10', 'No Charge', 'No Charge', '30', '30', '50', '50', 'Full Price', '400', '25', '25', '10', '10', '30', '30', 'Full Price', '60', 'Full Price', '75', 'Full Price', '$450 per stay', 'Full Price', '350', '6271', 'Additional Plan Benefits and Features -  Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available')
-- ('UHC Silver-X Virtual Access (Unlimited $0 Virtual) - HMO', '517.50', '3850', '9450', 'No Charge', 'No Charge', 'No Charge', 'No Charge', 'Full Price', '40%', 'Full Price', '40%', 'Full Price', '40%', '10', '10', '3', '3', 'Full Price', '100', 'Full Price', '40%', 'Full Price', '50%', 'Full Price', '40%', 'Full Price', '40%', '6272', 'Additional Plan Benefits and Features - Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Plan with Galileo: Get unlimited $0 virtual care through the Galileo app with a UnitedHealthcare Virtual plan')
-- ('UHC Gold-X Advantage+ ($0 PCP, Adult Dental + Vision) - HMO', '528.31', '1500', '7000', 'No Charge', 'No Charge', 'No Charge', 'No Charge', '40', '40', '65', '65', '250', '250', '10', '10', '1', '1', '50', '50', 'Full Price', '30%', 'Full Price', '40%', 'Full Price', '20%', 'Full Price', '20%', '6404', 'Additional Plan Benefits and Features - Digital Fitness Classes from One Pass: With on-demand and livestreaming digital fitness classes from One Pass™ you can get all the fitness you want at no additional cost, Earn a $100 prepaid Visa card : Earn a $100 reward on a prepaid Visa card upon completion of five activities, Walgreens Discount: 20% off Walgreens-brand health and wellness products, $0 Insulin: Insulin is available at a $0 out-of-pocket cost on select plans in certain states, Virtual Urgent Care: Get the care you need with a virtual visit, Virtual Primary Care: Low-cost virtual primary visits are available, In-Person Gym Access: With a One Pass™ membership from a UnitedHealthcare Individual & Family ACA Marketplace plan, you can pick your favorite network gym location and get a membership for no additional cost, Adult Vison: Adult vision coverage included in your plan with a $0 copay for a routine vision exam and up to $130 in frame coverage every 12 months, Adult Dental: Adult dental coverage included in your plan with a $0 copay for 2 periodic oral evaluation per calendar year. An annual maximum of $1,000 of additional covered dental work is included in the plan')


-- Insert user data into Users table


-- Insert user conditions into UserHealthConditions table


-- Insert user family conditions into FamilyHealthConditions table


-- Insert information about user's health and plan spending into
-- UserHealthInformation table